//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobOpeningsDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    [Bind(Exclude ="Locations, Departments")]
    public partial class Job
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int locationId { get; set; }

        public IEnumerable<SelectListItem> Locations { get; set; }
        public int departmentId { get; set; }
        public IEnumerable<SelectListItem> Departments { get; set; }

        public Nullable<System.DateTime> closingDate { get; set; }
    }
}
